### ISSUE TITLE
@ngx-loading-bar/router - Compiler Error

### ISSUE THREAD

**Issue by rpvsen** [aitboudad/ngx-loading-bar#117]
I am trying to user @ngx-loading-bar/router npm package with the help of [link](https://www.npmjs.com/package/@ngx-loading-bar/router). But i am getting below error while run my project.

WARNING in ./node_modules/@ngx-loading-bar/core/fesm5/ngx-loading-bar-core.js
167:155-161 "export 'inject' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compiler.js:506:17)
    at D:\Project\working_code\RemoveCommit\aiqui\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:477:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./node_modules/@ngx-loading-bar/core/fesm5/ngx-loading-bar-core.js
 @ ./node_modules/@ngx-loading-bar/router/fesm5/ngx-loading-bar-router.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/@ngx-loading-bar/core/fesm5/ngx-loading-bar-core.js
167:59-75 "export 'defineInjectable' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compiler.js:506:17)
    at D:\Project\working_code\RemoveCommit\aiqui\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\Project\working_code\RemoveCommit\aiqui\node_modules\webpack\lib\Compilation.js:477:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./node_modules/@ngx-loading-bar/core/fesm5/ngx-loading-bar-core.js
 @ ./node_modules/@ngx-loading-bar/router/fesm5/ngx-loading-bar-router.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

My package summary:

    "@angular/animations": "^5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/compiler-cli": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/platform-server": "~5.0.0",
    "@angular/router": "~5.0.0",
    "@ngx-loading-bar/core": "^4.1.1",
    "@ngx-loading-bar/router": "^4.1.1",

**Comment by aitboudad** [comment]
the version `4` of ngx-loading-bar require angular V7,
in your case, you may try with `V2` which is compatible with angular `V5`

**Comment by rpvsen** [comment]
> the version `4` of ngx-loading-bar require angular V7,
> in your case, you may try with `V2` which is compatible with angular `V5`

Thanks @aitboudad .
