### ISSUE TITLE
Angular 9 - IVY

### ISSUE THREAD

**Issue by hugoj-goncalves** [aitboudad/ngx-loading-bar#150]
`Compiling @ngx-loading-bar/http-client : es2015 as esm2015
Error: Error on worker #3: Error: Tried to overwrite C:/path/node_modules/@ngx-loading-bar/http-client/loading-bar.interceptor.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
    at NewEntryPointFileWriter.InPlaceFileWriter.writeFileAndBackup (C:\path\node_modules\@angular\compiler-cli\ngcc\src\writing\in_place_file_writer.js:37:23)
    at NewEntryPointFileWriter.writeFile (C:\path\node_modules\@angular\compiler-cli\ngcc\src\writing\new_entry_point_file_writer.js:64:53)
    at C:\path\node_modules\@angular\compiler-cli\ngcc\src\writing\new_entry_point_file_writer.js:46:69
    at Array.forEach (<anonymous>)
    at NewEntryPointFileWriter.writeBundle (C:\path\node_modules\@angular\compiler-cli\ngcc\src\writing\new_entry_point_file_writer.js:46:30)
    at ClusterWorker.compile (C:\path\node_modules\@angular\compiler-cli\ngcc\src\main.js:173:32)
    at Worker.<anonymous> (C:\path\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\worker.js:44:42)      
    at Worker.emit (events.js:210:5)
    at process.<anonymous> (internal/cluster/worker.js:30:12)
    at process.emit (events.js:210:5)
    at ClusterMaster.onWorkerMessage (C:\path\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:158:27)
    at C:\path\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:46:95
    at ClusterMaster.<anonymous> (C:\path\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:238:57)
    at step (C:\path\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\path\node_modules\tslib\tslib.js:117:57)
    at C:\path\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\path\node_modules\tslib\tslib.js:106:16)
    at EventEmitter.<anonymous> (C:\path\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:232:32)
    at EventEmitter.emit (events.js:210:5)`

Any ideas how to fix this? 😢

**Comment by aitboudad** [comment]
probably a permission issue, try to remove `node_modules` folder and try `npm install` again.

**Comment by hugoj-goncalves** [comment]
Well, looks like you're right. Sorry.
