### ISSUE TITLE
NullInjectorError: StaticInjectorError(AppModule)[LoadingBarComponent -> LoadingBarService]

### ISSUE THREAD

**Issue by manilioz** [aitboudad/ngx-loading-bar#173]
main.79c2f2db8d9e0004830c.js:19013 ERROR NullInjectorError: StaticInjectorError(AppModule)[LoadingBarComponent -> 
   LoadingBarService]: 
  StaticInjectorError(Platform: core)[LoadingBarComponent -> LoadingBarService]: 
    NullInjectorError: No provider for LoadingBarService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get 
    at resolveToken (https://example.com/main.79c2f2db8d9e0004830c.js:26941:24)
    at tryResolveToken (https://example.com/main.79c2f2db8d9e0004830c.js:26885:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get 
    at resolveToken (https://example.com/main.79c2f2db8d9e0004830c.js:26941:24)
    at tryResolveToken (https://example.com/main.79c2f2db8d9e0004830c.js:26885:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get 
    at resolveNgModuleDep (https://example.com/main.79c2f2db8d9e0004830c.js:35224:29)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get 
    at resolveDep (https://example.com/main.79c2f2db8d9e0004830c.js:36271:45)

I facing this problem even though I  included LoadingBarModule in app.module.ts.
It works well in development mode but not works in production(ng build --prod). 
How to fix it.
Thanks in advance.

**Comment by aitboudad** [comment]
Could you please ensure you're using the latest version of `ngx-loading-bar` which is `v5.1.0` and delete and reinstall `node_modules`.
