### ISSUE TITLE
Ngx-loading bar runtime error when content-type : undefined

### ISSUE THREAD

**Issue by shiv9604** [aitboudad/ngx-loading-bar#201]
**Steps to reproduce :**

1. Use ngx-loading bar in angular app.
2. Make a request with content-type undefined for file upload (Which i tried) but you can also try with the normal request.
3. When the request is made from the UI getting the following error.

**Error :-**
core.js:6210 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
at http.js:105:1
at Array.forEach (<anonymous>)
at HttpHeaders.lazyInit (http.js:99:1)
at HttpHeaders.init (http.js:203:1)
at HttpHeaders.has (http.js:121:1)
at LoadingBarInterceptor.intercept (ngx-loading-bar-http-client.js:15:1)
at HttpInterceptorHandler.handle (http.js:1290:1)
at HttpXsrfInterceptor.intercept (http.js:1931:1)
at HttpInterceptorHandler.handle (http.js:1290:1)
at HttpInterceptingHandler.handle (http.js:1981:1)
at http.js:105:1
at Array.forEach (<anonymous>)
at HttpHeaders.lazyInit (http.js:99:1)
at HttpHeaders.init (http.js:203:1)
at HttpHeaders.has (http.js:121:1)
at LoadingBarInterceptor.intercept (ngx-loading-bar-http-client.js:15:1)
at HttpInterceptorHandler.handle (http.js:1290:1)
at HttpXsrfInterceptor.intercept (http.js:1931:1)
at HttpInterceptorHandler.handle (http.js:1290:1)
at HttpInterceptingHandler.handle (http.js:1981:1)
at resolvePromise (zone-evergreen.js:798:1)
at resolvePromise (zone-evergreen.js:750:1)
at zone-evergreen.js:860:1
at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
at Object.onInvokeTask (core.js:28578:1)
at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
at Zone.runTask (zone-evergreen.js:167:1)
at drainMicroTaskQueue (zone-evergreen.js:569:1)
at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484:1)
at invokeTask (zone-evergreen.js:1621:1)

**Comment by aitboudad** [comment]
This issue has been fixed as part of [v7.0.0](https://github.com/aitboudad/ngx-loading-bar/releases/tag/v7.0.0) release.

**Comment by shiv9604** [comment]
Thanks for your contribution @aitboudad, I appreciate your efforts for maintaining ngx loader lib. Keep Up!
